# Pandas : dataframe 구현을 가능하게 해주는 라이브러리

- pandas는 파이썬에서 데이터를 분석하고 처리하는데 가장 많이 사용하고 강력한 라이브러리
- 엑셀처럼 테이블 형식의 표 데이터를 핸들링이 가능하면 이 개념을 우리는 데이터 프레임(Dataframe) 구조라고 정의
- csv, excel, database, 웹 데이터 (structured data) 등을 수집해서 정리, 가공, 데이터 분석, 데이터 인사이트 도출
- 이때, 주피터노트북이 이 과정에서 가장 좋은 도구로 평가 받고 있음
    - 영상, 이미지, 신호, 주파수 등 (unstructured data) -> json으로 정형데이터화 할 수 있음
    - Pandas에서 정형데이터를 지원
    - 결론적으로, 테이블 형식의구조화된 데이터를 핸들하고 분석할때 최적화된 도구이자 라이브러리

In [1]:
import pandas as pd

In [3]:
x = pd.Series([7,3,5,8], index = ['서울', '천안', '아산', '평택'])
x

서울    7
천안    3
아산    5
평택    8
dtype: int64

In [4]:
print(x['서울'])

7

In [8]:
print(x['서울'],x['천안'])

7 3

In [9]:
가져올목록 = ['서울','천안']
print(x[가져올목록])

서울    7
천안    3
dtype: int64

In [10]:
print(x[['서울','천안']])

서울    7
천안    3
dtype: int64

In [11]:
x.index

Index(['서울', '천안', '아산', '평택'], dtype='object')

In [13]:
sorted(x.index)

['서울', '아산', '천안', '평택']

In [15]:
x.values

array([7, 3, 5, 8])

In [16]:
a = [1,3,2,4,2,3]
x = pd.Series(a)

In [17]:
x

0    1
1    3
2    2
3    4
4    2
5    3
dtype: int64

In [18]:
pd.unique(x)

array([1, 3, 2, 4])

In [19]:
data = {
    '이름' : ['강동균','김영곤','김현수','노경환'],
    '점수' : [90,83,93,88],
    '학년' : [4,3,4,3]
}

In [20]:
df = pd.DataFrame(data)

In [21]:
df

    이름  점수  학년
0  강동균  90   4
1  김영곤  83   3
2  김현수  93   4
3  노경환  88   3

In [40]:
df.to_csv('student.csv', encoding = 'euc-kr')
#utf-8(-sig), euc-kr,cp949

In [41]:
df2 = pd.read_csv('student.csv', encoding = 'euc-kr', index_col = 0)

In [42]:
df2

    이름  점수  학년
0  강동균  90   4
1  김영곤  83   3
2  김현수  93   4
3  노경환  88   3

In [43]:
data = {'age' : [21,22,33,23,31,35,24,35,46,29],
        'name' : ['동균','현수','영곤','경환','준한','지민','창석','경현','영준','순나'],
        'height' : [180,178,167,168,179,164,174,175,173,177]}

In [44]:
df = pd.DataFrame(data)

In [45]:
df

   age name  height
0   21   동균     180
1   22   현수     178
2   33   영곤     167
3   23   경환     168
4   31   준한     179
5   35   지민     164
6   24   창석     174
7   35   경현     175
8   46   영준     173
9   29   순나     177

In [46]:
df = pd.DataFrame(data, columns = ['name','age','height'])
df

  name  age  height
0   동균   21     180
1   현수   22     178
2   영곤   33     167
3   경환   23     168
4   준한   31     179
5   지민   35     164
6   창석   24     174
7   경현   35     175
8   영준   46     173
9   순나   29     177

In [47]:
df['name']

0    동균
1    현수
2    영곤
3    경환
4    준한
5    지민
6    창석
7    경현
8    영준
9    순나
Name: name, dtype: object

In [50]:
df['name'].head(3)

0    동균
1    현수
2    영곤
Name: name, dtype: object

In [52]:
df.tail()

  name  age  height
5   지민   35     164
6   창석   24     174
7   경현   35     175
8   영준   46     173
9   순나   29     177

In [53]:
df.shape

(10, 3)

In [54]:
df.columns

Index(['name', 'age', 'height'], dtype='object')

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   age     10 non-null     int64
 2   height  10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

y = ax+bx+cx+d

y : target

x : column, feature

In [58]:
df[['name','age']]

  name  age
0   동균   21
1   현수   22
2   영곤   33
3   경환   23
4   준한   31
5   지민   35
6   창석   24
7   경현   35
8   영준   46
9   순나   29

In [59]:
df.iloc[0]

name       동균
age        21
height    180
Name: 0, dtype: object

In [61]:
df.loc[1, 'name']

'현수'

In [64]:
data = [[1,2],[3,4],[5,6]]
df = pd.DataFrame(data, columns = ['first','second'])

In [65]:
df

   first  second
0      1       2
1      3       4
2      5       6

In [70]:
df.iloc[1]

first     3
second    4
Name: 1, dtype: int64

In [69]:
df.iloc[:,-1]

0    2
1    4
2    6
Name: second, dtype: int64

In [71]:
df.iloc[:]

   first  second
0      1       2
1      3       4
2      5       6

In [72]:
df.iloc[-2]

first     3
second    4
Name: 1, dtype: int64

dataframe연습

In [89]:
df = pd.DataFrame({
    "이름": ["철수", "영희", "민수", "지영"],
    "나이": [25, 30, 28, 35],
    "부서": ["영업", "개발", "개발", "인사"],
    "연봉": [3500, 5000, 4800, 4200]})

In [90]:
df

   이름  나이  부서    연봉
0  철수  25  영업  3500
1  영희  30  개발  5000
2  민수  28  개발  4800
3  지영  35  인사  4200

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      object
 1   나이      4 non-null      int64
 2   부서      4 non-null      object
 3   연봉      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [76]:
df.columns

Index(['이름', '나이', '부서', '연봉'], dtype='object')

In [78]:
df.describe()

              나이           연봉
count   4.000000     4.000000
mean   29.500000  4375.000000
std     4.203173   675.154303
min    25.000000  3500.000000
25%    27.250000  4025.000000
50%    29.000000  4500.000000
75%    31.250000  4850.000000
max    35.000000  5000.000000

In [79]:
df.iloc[0]

이름      철수
나이      25
부서      영업
연봉    3500
Name: 0, dtype: object

In [80]:
df.loc[1,"이름"]

'영희'

In [81]:
df.iloc[0:2]

   이름  나이  부서    연봉
0  철수  25  영업  3500
1  영희  30  개발  5000

In [82]:
df.loc[:,['이름','부서']]

   이름  부서
0  철수  영업
1  영희  개발
2  민수  개발
3  지영  인사

In [83]:
df.head()

   이름  나이  부서    연봉
0  철수  25  영업  3500
1  영희  30  개발  5000
2  민수  28  개발  4800
3  지영  35  인사  4200

In [91]:
#파생변수
df['연봉_원'] = df['연봉']*10000
df

   이름  나이  부서    연봉      연봉_원
0  철수  25  영업  3500  35000000
1  영희  30  개발  5000  50000000
2  민수  28  개발  4800  48000000
3  지영  35  인사  4200  42000000

In [92]:
df = df.rename(columns = {'연봉' : '연봉_만원'})
df

   이름  나이  부서  연봉_만원      연봉_원
0  철수  25  영업   3500  35000000
1  영희  30  개발   5000  50000000
2  민수  28  개발   4800  48000000
3  지영  35  인사   4200  42000000

In [87]:
df.drop(columns = ['연봉_원'])
df

   이름  나이  부서  연봉_만원      연봉_원
0  철수  25  영업   3500  35000000
1  영희  30  개발   5000  50000000
2  민수  28  개발   4800  48000000
3  지영  35  인사   4200  42000000

In [88]:
df2 = df.drop(columns = ['연봉_원'])
df2

   이름  나이  부서  연봉_만원
0  철수  25  영업   3500
1  영희  30  개발   5000
2  민수  28  개발   4800
3  지영  35  인사   4200

In [93]:
df.drop(columns = ['연봉_원'], inplace = True)
df.head()

   이름  나이  부서  연봉_만원
0  철수  25  영업   3500
1  영희  30  개발   5000
2  민수  28  개발   4800
3  지영  35  인사   4200