In [3]:
mamba install pandas
mamba install numpy

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 2.205299999952316 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge
mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.094800000011921 seconds
All requested packages already installed.

In [4]:
import pandas as pd
import numpy as np

In [5]:
data = {'학번': range(2000, 2010),
       '전공성적1' : [85, 95, 75, np.nan , 100, 100, 95, 85, 80, 85], 
       '전공성적2' : [95, 95, 100, 80, 100, 100, 95, 85, np.nan, 85],
       '전공성적3' : [np.nan, np.nan, np.nan, np.nan, 100, np.nan, 95, 85, np.nan, 85]}

In [6]:
df = pd.DataFrame(data)
df

     학번  전공성적1  전공성적2  전공성적3
0  2000   85.0   95.0    NaN
1  2001   95.0   95.0    NaN
2  2002   75.0  100.0    NaN
3  2003    NaN   80.0    NaN
4  2004  100.0  100.0  100.0
5  2005  100.0  100.0    NaN
6  2006   95.0   95.0   95.0
7  2007   85.0   85.0   85.0
8  2008   80.0    NaN    NaN
9  2009   85.0   85.0   85.0

In [7]:
df.info

<bound method DataFrame.info of      학번  전공성적1  전공성적2  전공성적3
0  2000   85.0   95.0    NaN
1  2001   95.0   95.0    NaN
2  2002   75.0  100.0    NaN
3  2003    NaN   80.0    NaN
4  2004  100.0  100.0  100.0
5  2005  100.0  100.0    NaN
6  2006   95.0   95.0   95.0
7  2007   85.0   85.0   85.0
8  2008   80.0    NaN    NaN
9  2009   85.0   85.0   85.0>

In [9]:
df.isnull()

      학번  전공성적1  전공성적2  전공성적3
0  False  False  False   True
1  False  False  False   True
2  False  False  False   True
3  False   True  False   True
4  False  False  False  False
5  False  False  False   True
6  False  False  False  False
7  False  False  False  False
8  False  False   True   True
9  False  False  False  False

In [11]:
df.isnull().sum()

학번       0
전공성적1    1
전공성적2    1
전공성적3    6
dtype: int64

In [12]:
df2 = df.dropna()
df2

     학번  전공성적1  전공성적2  전공성적3
4  2004  100.0  100.0  100.0
6  2006   95.0   95.0   95.0
7  2007   85.0   85.0   85.0
9  2009   85.0   85.0   85.0

In [13]:
# mean or 0 으로 주 대체
df3 = df.fillna(0, inplace = True)
df3

     학번  전공성적1  전공성적2  전공성적3
0  2000   85.0   95.0    0.0
1  2001   95.0   95.0    0.0
2  2002   75.0  100.0    0.0
3  2003    0.0   80.0    0.0
4  2004  100.0  100.0  100.0
5  2005  100.0  100.0    0.0
6  2006   95.0   95.0   95.0
7  2007   85.0   85.0   85.0
8  2008   80.0    0.0    0.0
9  2009   85.0   85.0   85.0

In [21]:
def employee(n=200, seed=42):
    rng = np.random.default_rng(seed)                  # 재현 가능한 난수 생성기
    부서 = rng.choice(["영업", "개발", "인사", "마케팅"], n, p=[0.35, 0.35, 0.10, 0.20])
    교육 = rng.choice(["고졸", "대졸", "석사", "박사"], n, p=[0.20, 0.50, 0.25, 0.05])
    경력 = rng.integers(0, 21, n)                       # 0~20년
    나이 = (24 + 경력 + rng.integers(-2, 3, n)).astype(int)
    # 연봉(만원): 기본 + 경력 + 교육보너스 + 부서보너스 + 약간의 무작위
    교육보너스 = pd.Series(교육).map({"고졸": 0, "대졸": 300, "석사": 700, "박사": 1200}).values
    부서보너스 = pd.Series(부서).map({"영업": 200, "개발": 500, "인사": 0, "마케팅": 150}).values
    연봉 = 3000 + 경력 * 150 + 교육보너스 + 부서보너스 + rng.normal(0, 300, n)
    df = pd.DataFrame({
        "사번": range(1001, 1001 + n),
        "부서": 부서,
        "교육수준": 교육,
        "나이": 나이,
        "경력": 경력,
        "연봉": 연봉.round(0).astype(int),
    })
    return df

employee()

       사번   부서 교육수준  나이  경력    연봉
0    1001   인사   석사  26   0  4074
1    1002   개발   박사  31   6  5524
2    1003  마케팅   대졸  34  10  5059
3    1004   개발   고졸  45  19  5627
4    1005   영업   고졸  37  15  5103
..    ...  ...  ...  ..  ..   ...
195  1196   영업   대졸  38  13  5527
196  1197   개발   석사  36  11  6255
197  1198  마케팅   대졸  33   7  4504
198  1199   영업   대졸  46  20  6561
199  1200   영업   대졸  35  10  4672

[200 rows x 6 columns]

In [19]:
df2 = employee(100).copy()

In [20]:
df2.head()

     사번   부서 교육수준  나이  경력    연봉
0  1001   인사   석사  42  20  6612
1  1002   개발   대졸  41  16  6169
2  1003  마케팅   대졸  32   6  4274
3  1004   개발   박사  46  20  7746
4  1005   영업   석사  33  10  5841

In [22]:
df2.loc[2:5, '연봉'] = np.nan
df2.loc[7, '교육수준'] = np.nan

In [23]:
df2

      사번   부서 교육수준  나이  경력      연봉
0   1001   인사   석사  42  20  6612.0
1   1002   개발   대졸  41  16  6169.0
2   1003  마케팅   대졸  32   6     NaN
3   1004   개발   박사  46  20     NaN
4   1005   영업   석사  33  10     NaN
..   ...  ...  ...  ..  ..     ...
95  1096   개발   고졸  34   8  4325.0
96  1097   개발   대졸  26   2  3620.0
97  1098   영업   석사  32   7  4712.0
98  1099   영업   고졸  44  19  6182.0
99  1100  마케팅   대졸  33   8  4807.0

[100 rows x 6 columns]

In [24]:
df2.isnull().sum()

사번      0
부서      0
교육수준    1
나이      0
경력      0
연봉      4
dtype: int64

In [28]:
df2['연봉'] = df2['연봉'].fillna(df2['연봉'].mean())
df2['연봉']

0     6612.000000
1     6169.000000
2     5208.458333
3     5208.458333
4     5208.458333
         ...
95    4325.000000
96    3620.000000
97    4712.000000
98    6182.000000
99    4807.000000
Name: 연봉, Length: 100, dtype: float64

중복값

In [31]:
df2.duplicated().sum()

np.int64(0)

 - 이상치는 관찰의 대상

# IQR = 이상치를 처리하는 방법
 - IQR : Q3 - Q1
 - 정상범위 : Q1 - 1.5*IQR ~ Q3 + 1.5*IQR
 - 정상범위 외의 값을 Outlier로 판단

In [34]:
Q1 = df2['연봉'].quantile(0.25)
Q3 = df2['연봉'].quantile(0.75)
IQR = Q3 - Q1

Lower = Q1 - 1.5*IQR
Upper = Q3 + 1.5*IQR

print(f"Q1 : {Q1}, Q3 : {Q3}, 하한 : {Lower}, 상한 : {Upper}")
print(f"정상범위 : {Lower} ~ {Upper}")

Q1 : 4346.0, Q3 : 6136.0, 하한 : 1661.0, 상한 : 8821.0
정상범위 : 1661.0 ~ 8821.0