# AI 
 - machine Learning(= training = fitting) 최적화 시키는 것
 - deep Learning
 - + reinforcement(강화학습)

# 데이터 핸들링 
 - 데이터 변환 : 데이터 타입, 인코딩, 스케일링, 파생변수
 - 모델이 이해할 수 있는 형태의 데이터 ()
 - 스케일링 : 균일하게 만들어주는 것
 - astype
 - map
 - apply
 - 범주형 : 원핫인코딩(문자 => 숫자)
 - 스케일링(표준화/정규화)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/직원_실습데이터.csv', encoding = 'utf-8-sig')
df.head()

     사번   부서 교육수준  나이  경력    연봉
0  1001   인사   석사  26   0  4074
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627
4  1005   영업   고졸  37  15  5103

In [3]:
df.shape

(200, 6)

# 컬럼명

# 결측치 파악
# 기초동계량 분석
# 행과 열의 개수
# 자료형

In [4]:
#칼럼명
df.columns.tolist()

['사번', '부서', '교육수준', '나이', '경력', '연봉']

In [5]:
#결측치
df.isnull().sum()

사번      0
부서      0
교육수준    0
나이      0
경력      0
연봉      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사번      200 non-null    int64
 1   부서      200 non-null    object
 2   교육수준    200 non-null    object
 3   나이      200 non-null    int64
 4   경력      200 non-null    int64
 5   연봉      200 non-null    int64
dtypes: int64(4), object(2)
memory usage: 9.5+ KB

In [7]:
#자료형
df.dtypes

사번       int64
부서      object
교육수준    object
나이       int64
경력       int64
연봉       int64
dtype: object

In [8]:
#기초통계량
df.describe

<bound method NDFrame.describe of        사번   부서 교육수준  나이  경력    연봉
0    1001   인사   석사  26   0  4074
1    1002   개발   박사  31   6  5524
2    1003  마케팅   대졸  34  10  5059
3    1004   개발   고졸  45  19  5627
4    1005   영업   고졸  37  15  5103
..    ...  ...  ...  ..  ..   ...
195  1196   영업   대졸  38  13  5527
196  1197   개발   석사  36  11  6255
197  1198  마케팅   대졸  33   7  4504
198  1199   영업   대졸  46  20  6561
199  1200   영업   대졸  35  10  4672

[200 rows x 6 columns]>

범주형 데이터값의분포 분석

In [9]:
df['부서'].value_counts()

부서
개발     71
영업     71
마케팅    35
인사     23
Name: count, dtype: int64

In [10]:
#결측치 확인 
df.isnull().sum()

사번      0
부서      0
교육수준    0
나이      0
경력      0
연봉      0
dtype: int64

In [11]:
#중복값 왁인
df.duplicated().sum()

np.int64(0)

In [12]:
#중복값 제거

## 자료형 변환

In [13]:
df.dtypes

사번       int64
부서      object
교육수준    object
나이       int64
경력       int64
연봉       int64
dtype: object

In [14]:
df2 = df.copy()

In [15]:
df2 = df2['경력'].astype(float)

In [16]:
df2.dtypes

dtype('float64')

# 값 변환 - map/apply

In [17]:
edu_level = {
    "고졸" : 1,
    "대졸" : 2,
    "석사" : 3,
    "박사" : 4
}

In [18]:
df["교육수준"] = df["교육수준"].map(edu_level)
df.head()

     사번   부서  교육수준  나이  경력    연봉
0  1001   인사     3  26   0  4074
1  1002   개발     4  31   6  5524
2  1003  마케팅     2  34  10  5059
3  1004   개발     1  45  19  5627
4  1005   영업     1  37  15  5103

In [19]:
def 연봉등급(연봉):
    if 연봉 >= 6000:
        return "상위"
    elif 연봉 >= 4500:
        return "중위"
    else:
        return "하위"

## apply를 이용한 데이터 적용

In [20]:
df["연봉등급"] = df["연봉"].apply(연봉등급)

In [21]:
df.head()

     사번   부서  교육수준  나이  경력    연봉 연봉등급
0  1001   인사     3  26   0  4074   하위
1  1002   개발     4  31   6  5524   중위
2  1003  마케팅     2  34  10  5059   중위
3  1004   개발     1  45  19  5627   중위
4  1005   영업     1  37  15  5103   중위

# 데이터 핸들링
## 데이터 제거/삭제
## 데이터 정제
## 데이터 전처리

5. 범주형 인코딩

1) 라벨 인코딩 : 각 범주에 번호를 부여
2) 원핫 인코딩 : 범주별로 0/1 컬럼 생성

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
# object = 생성자 꼴
#fit_transform() : 자동으로 라벨을 붙여줌
le = LabelEncoder()
df['연봉등급_라벨'] = le.fit_transform(df['연봉등급'])
df.head()

     사번   부서  교육수준  나이  경력    연봉 연봉등급  연봉등급_라벨
0  1001   인사     3  26   0  4074   하위        2
1  1002   개발     4  31   6  5524   중위        1
2  1003  마케팅     2  34  10  5059   중위        1
3  1004   개발     1  45  19  5627   중위        1
4  1005   영업     1  37  15  5103   중위        1

In [25]:
부서_원핫 = pd.get_dummies(df['부서'],prefix = '부서', dtype = int)
부서_원핫.head()

   부서_개발  부서_마케팅  부서_영업  부서_인사
0      0       0      0      1
1      1       0      0      0
2      0       1      0      0
3      1       0      0      0
4      0       0      1      0

구분	MinMaxScaler	StandardScaler
변환 기준	최소값과 최대값	평균과 표준편차

In [ ]:
scale = ['나이', '경력','연봉']