In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/직원_실습데이터.csv', encoding = 'utf-8-sig')
df.head()

     사번   부서 교육수준  나이  경력    연봉
0  1001   인사   석사  26   0  4074
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627
4  1005   영업   고졸  37  15  5103

In [3]:
df.shape

(200, 6)

조건 필터링 - 불리언 인덱싱

In [4]:
high_salary = df[df['연봉']>=5000]
print(f"연봉 5000이상 : {len(high_salary)}명")
print(high_salary.head(3))

연봉 5000이상 : 108명
     사번   부서 교육수준  나이  경력    연봉
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627

2. 여러 조건 결합 - AND(&), OR(|)

In [57]:
#AND 개발 부서이면서 연봉이 5000이상
개발_연봉 = df[(df['연봉']>=5000)&(df['부서']=='개발')]
print(f"개발 부서이면서 연봉 5000이상 : {len(개발_연봉)}명")

개발 부서이면서 연봉 5000이상 : 47명

In [58]:
#or : 박사 또는경력 15년 이상
박사_경력 = df[(df['경력']>=15)|(df['교육수준']=='박사')]
print(f"박사 또는 경력 15년 이상 : {len(박사_경력)}명")

박사 또는 경력 15년 이상 : 57명

In [59]:
# not : 인사 부서가 아닌 인원(!=)
인사 = df[(df['부서']!='인사')]
print(f"인사 부서가 아닌 인원 : {len(인사)}명")

인사 부서가 아닌 인원 : 177명

In [24]:
#isin/between-편리한 필터링

In [26]:
len(df[df['부서'].isin(['영업','마케팅'])])

106

In [29]:
#경력이 5~10년차
len(df[df['경력'].between(5,10)])

52

# query() - 조건을 문장처럼

In [32]:
result = df.query("부서 == '개발' and 연봉 >= 4500 and 경력 < 10")
print(f"조건만족 : {len(result)}명")
result.head()

조건만족 : 15명

       사번  부서 교육수준  나이  경력    연봉
1    1002  개발   박사  31   6  5524
37   1038  개발   석사  26   4  4558
40   1041  개발   석사  31   6  5172
53   1054  개발   대졸  31   5  5033
106  1107  개발   대졸  31   8  4844

## sort_values

In [42]:
#연봉 top3(많은 사람) - 내림차순
high_salary = df.sort_values(by = ['연봉'], ascending = False)
high_salary.head(3)[["사번","부서","연봉"]]

       사번  부서    연봉
61   1062  개발  7224
148  1149  개발  7088
164  1165  개발  7006

In [ ]:
#for i in res['부서'].unique():
#    res = data[data['부서']==i].sort_values(by="연봉",ascending= False)[:3]
#    print(f"부서 : {i}\n\n",res)

In [73]:
#여러기준 : 부서 오름차순 -> 같은 부서 안에서 많은 사람부터 정렬

for i in df['부서'].unique():
    print(df[df['부서']==i].sort_values(by = '연봉', ascending = False).head(3))
    print("\n")

       사번  부서 교육수준  나이  경력    연봉
42   1043  인사   대졸  43  19  6585
158  1159  인사   대졸  43  20  6347
55   1056  인사   석사  43  17  6128


       사번  부서 교육수준  나이  경력    연봉
61   1062  개발   석사  44  19  7224
148  1149  개발   대졸  44  19  7088
164  1165  개발   대졸  43  19  7006


       사번   부서 교육수준  나이  경력    연봉
23   1024  마케팅   박사  39  13  6455
103  1104  마케팅   대졸  40  18  6395
142  1143  마케팅   석사  45  19  6393


       사번  부서 교육수준  나이  경력    연봉
15   1016  영업   석사  43  17  6996
50   1051  영업   대졸  44  20  6909
168  1169  영업   대졸  45  19  6629

In [62]:
print(df.sort_values(by=['부서', '연봉'], ascending=[True, False]))

       사번  부서 교육수준  나이  경력    연봉
61   1062  개발   석사  44  19  7224
148  1149  개발   대졸  44  19  7088
164  1165  개발   대졸  43  19  7006
64   1065  개발   석사  42  17  6960
113  1114  개발   대졸  43  20  6894
..    ...  ..  ...  ..  ..   ...
30   1031  인사   고졸  29   5  3884
7    1008  인사   대졸  26   2  3814
20   1021  인사   대졸  22   0  3544
188  1189  인사   고졸  29   5  3215
86   1087  인사   고졸  27   1  3047

[200 rows x 6 columns]

In [48]:
print("연봉 TOP 3:\n", df.sort_values("연봉", ascending=False).head(3)[["사번", "부서", "연봉"]])

연봉 TOP 3:
        사번  부서    연봉
61   1062  개발  7224
148  1149  개발  7088
164  1165  개발  7006

In [52]:
#nlargest/nsmallest(정렬 대신 간편하게 데이터를 핸들링 정렬이 필요할때 사용)

df.nlargest(3,'연봉')[['사번','연봉']]

       사번    연봉
61   1062  7224
148  1149  7088
164  1165  7006

In [53]:
df.nsmallest(3,'연봉')[['사번','연봉']]

      사번    연봉
38  1039  2815
88  1089  2988
16  1017  3004