In [1]:
import pandas as pd

In [6]:
df1 = pd.DataFrame({'이름' : ['재원', '준석', '성훈', '수민', '희영', '소영'],
                     '성별' :['남자', '남자', '남자', '여자', '여자', '여자']})
df1

   이름  성별
0  재원  남자
1  준석  남자
2  성훈  남자
3  수민  여자
4  희영  여자
5  소영  여자

In [7]:
df2 = pd.DataFrame({'이름' : ['재원', '준석', '성훈', '수민', '희영', '소영'],
                     '키' :['180', '190', '176', '165', '170', '166']})
df2

   이름    키
0  재원  180
1  준석  190
2  성훈  176
3  수민  165
4  희영  170
5  소영  166

# merge : 공통된 컬럼을 기준으로 데이터 프레임을 결합하는 방법

In [8]:
df3 = pd.merge(df1,df2)
df3

   이름  성별    키
0  재원  남자  180
1  준석  남자  190
2  성훈  남자  176
3  수민  여자  165
4  희영  여자  170
5  소영  여자  166

In [9]:
df4 = pd.merge(df1,df2, on = '이름', how = 'inner')
df4

   이름  성별    키
0  재원  남자  180
1  준석  남자  190
2  성훈  남자  176
3  수민  여자  165
4  희영  여자  170
5  소영  여자  166

- inner : 양쪽에 모두 있는 데이터만 결합
- left : 왼쪽 데이터는 모두 유지, 오른쪽의 빈칸이나 결측치를 nan처리
- right : 오른쪽 데이터는 모두 유지
- outer : 양쪽 데이터를 모두 유지

In [10]:
df5 = pd.merge(df1,df2, on = '이름', how = 'left')
df5

   이름  성별    키
0  재원  남자  180
1  준석  남자  190
2  성훈  남자  176
3  수민  여자  165
4  희영  여자  170
5  소영  여자  166

In [11]:
df6 = pd.merge(df1,df2, on = '이름', how = 'right')
df6

   이름  성별    키
0  재원  남자  180
1  준석  남자  190
2  성훈  남자  176
3  수민  여자  165
4  희영  여자  170
5  소영  여자  166

In [16]:
df_cust = pd.read_csv('./data/customers.csv', encoding = 'utf-8-sig')
df_cust.head()

   고객ID   이름  지역   등급
0  C001  김철수  서울  VIP
1  C002  이영희  부산   일반
2  C003  박민수  서울  VIP
3  C004  정지영  대구   일반
4  C005  최현우  서울  VIP

In [17]:
df_ord = pd.read_csv('./data/orders.csv', encoding = 'utf-8-sig')
df_ord.head()

   주문ID  고객ID   상품       금액
0     1  C001  노트북  1500000
1     2  C001  마우스    30000
2     3  C002  키보드    50000
3     4  C003  모니터   300000
4     5  C003  노트북  1500000

In [18]:
inner = pd.merge(df_cust,df_ord, on = '고객ID', how = 'inner')
inner

   고객ID   이름  지역   등급  주문ID   상품       금액
0  C001  김철수  서울  VIP     1  노트북  1500000
1  C001  김철수  서울  VIP     2  마우스    30000
2  C002  이영희  부산   일반     3  키보드    50000
3  C003  박민수  서울  VIP     4  모니터   300000
4  C003  박민수  서울  VIP     5  노트북  1500000
5  C004  정지영  대구   일반     6  마우스    30000

In [19]:
left = pd.merge(df_cust,df_ord, on = '고객ID', how = 'left')
left

   고객ID   이름  지역   등급  주문ID   상품         금액
0  C001  김철수  서울  VIP   1.0  노트북  1500000.0
1  C001  김철수  서울  VIP   2.0  마우스    30000.0
2  C002  이영희  부산   일반   3.0  키보드    50000.0
3  C003  박민수  서울  VIP   4.0  모니터   300000.0
4  C003  박민수  서울  VIP   5.0  노트북  1500000.0
5  C004  정지영  대구   일반   6.0  마우스    30000.0
6  C005  최현우  서울  VIP   NaN  NaN        NaN

In [20]:
right = pd.merge(df_cust,df_ord, on = '고객ID', how = 'right')
right

   고객ID   이름   지역   등급  주문ID   상품       금액
0  C001  김철수   서울  VIP     1  노트북  1500000
1  C001  김철수   서울  VIP     2  마우스    30000
2  C002  이영희   부산   일반     3  키보드    50000
3  C003  박민수   서울  VIP     4  모니터   300000
4  C003  박민수   서울  VIP     5  노트북  1500000
5  C004  정지영   대구   일반     6  마우스    30000
6  C999  NaN  NaN  NaN     7  스피커    80000

In [21]:
outer = pd.merge(df_cust,df_ord, on = '고객ID', how = 'outer')
outer

   고객ID   이름   지역   등급  주문ID   상품         금액
0  C001  김철수   서울  VIP   1.0  노트북  1500000.0
1  C001  김철수   서울  VIP   2.0  마우스    30000.0
2  C002  이영희   부산   일반   3.0  키보드    50000.0
3  C003  박민수   서울  VIP   4.0  모니터   300000.0
4  C003  박민수   서울  VIP   5.0  노트북  1500000.0
5  C004  정지영   대구   일반   6.0  마우스    30000.0
6  C005  최현우   서울  VIP   NaN  NaN        NaN
7  C999  NaN  NaN  NaN   7.0  스피커    80000.0

# concat 결합

In [22]:
sales_feb = pd.read_csv('./data/sales_feb.csv', encoding = 'utf-8-sig')
sales_jan = pd.read_csv('./data/sales_jan.csv', encoding = 'utf-8-sig')

In [26]:
len(sales_jan)

12

In [25]:
len(sales_feb)

9

In [31]:
sales_df = pd.concat([sales_jan,sales_feb], ignore_index = True) #인덱스 리셋

In [32]:
sales_df

            날짜   지점     상품  수량    단가     매출
0   2024-01-03  판교점   샌드위치   5  5500  27500
1   2024-01-24  판교점    케이크   5  6500  32500
2   2024-01-21  판교점     라떼   2  6500  13000
3   2024-01-14  판교점   샌드위치   4  3000  12000
4   2024-01-14  홍대점    케이크   1  4000   4000
5   2024-01-27  강남점     라떼   4  4000  16000
6   2024-01-03  판교점     라떼   4  4000  16000
7   2024-01-22  홍대점  아메리카노   2  3000   6000
8   2024-01-07  홍대점  아메리카노   1  5500   5500
9   2024-01-03  홍대점    케이크   5  3000  15000
10  2024-01-17  강남점   샌드위치   3  5500  16500
11  2024-01-31  판교점  아메리카노   5  5500  27500
12  2024-02-26  홍대점    케이크   2  3000   6000
13  2024-02-21  판교점    케이크   4  5500  22000
14  2024-02-11  강남점   샌드위치   5  5500  27500
15  2024-02-28  홍대점     라떼   3  3000   9000
16  2024-02-12  강남점  아메리카노   5  6500  32500
17  2024-02-10  판교점   샌드위치   5  3000  15000
18  2024-02-26  홍대점    케이크   2  6500  13000
19  2024-02-11  강남점    케이크   5  3000  15000
20  2024-02-03  강남점  아메리카노   2  6500  13000

In [35]:
keyed = pd.concat([sales_jan, sales_feb], keys = ['1월','2월']) #grouping
keyed

               날짜   지점     상품  수량    단가     매출
1월 0   2024-01-03  판교점   샌드위치   5  5500  27500
   1   2024-01-24  판교점    케이크   5  6500  32500
   2   2024-01-21  판교점     라떼   2  6500  13000
   3   2024-01-14  판교점   샌드위치   4  3000  12000
   4   2024-01-14  홍대점    케이크   1  4000   4000
   5   2024-01-27  강남점     라떼   4  4000  16000
   6   2024-01-03  판교점     라떼   4  4000  16000
   7   2024-01-22  홍대점  아메리카노   2  3000   6000
   8   2024-01-07  홍대점  아메리카노   1  5500   5500
   9   2024-01-03  홍대점    케이크   5  3000  15000
   10  2024-01-17  강남점   샌드위치   3  5500  16500
   11  2024-01-31  판교점  아메리카노   5  5500  27500
2월 0   2024-02-26  홍대점    케이크   2  3000   6000
   1   2024-02-21  판교점    케이크   4  5500  22000
   2   2024-02-11  강남점   샌드위치   5  5500  27500
   3   2024-02-28  홍대점     라떼   3  3000   9000
   4   2024-02-12  강남점  아메리카노   5  6500  32500
   5   2024-02-10  판교점   샌드위치   5  3000  15000
   6   2024-02-26  홍대점    케이크   2  6500  13000
   7   2024-02-11  강남점    케이크   5  3000  15000
   8   2024-02-03  강남점  아메리카노   2  6500  13000