## 프로젝트 1. 이커머스 주문 데이터 분석 프로젝트

### 사용 데이터

- `project2_customers.csv`
- `project2_products.csv`
- `project2_orders_q1.csv`
- `project2_orders_q2.csv`

### 프로젝트 상황

이커머스 기업에서 2026년 상반기 주문 데이터를 분석하여 매출, 이익, 고객 특성별 구매 패턴을 확인하려고 합니다.

### 수행 조건

1. 고객, 상품, Q1 주문, Q2 주문 데이터를 불러오시오.
2. Q1 주문 데이터와 Q2 주문 데이터를 `concat`으로 합치시오.
3. 결측치와 중복치를 확인하고 처리하시오.
4. 주문일자를 날짜형으로 변환하고 주문월, 요일 변수를 생성하시오.
5. 주문 데이터에 고객 정보를 `merge`하시오.
6. 주문 데이터에 상품 정보를 `merge`하시오.
7. `join`을 사용하여 주문 데이터에 상품 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.
8. `iloc`로 앞 5행과 일부 컬럼을 선택하시오.
8. `loc`로 VIP 고객 주문만 선택하시오.
9. 총매출액, 할인액, 순매출액, 이익, 실매출액 변수를 생성하시오.
10. 전자기기 카테고리의 고액 정상 주문을 필터링하고 정렬하시오.
11. 카테고리별 주문건수, 판매수량, 실매출액, 실이익을 집계하시오.
12. 회원등급을 순서형 인코딩하시오.
13. 카테고리, 지역, 결제수단, 판매채널을 원-핫 인코딩하시오.
14. 매출 관련 수치형 컬럼을 스케일링하시오.
15. 최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.

---

## 프로젝트 2. 스마트팩토리 생산 품질 데이터 분석 프로젝트

### 사용 데이터

- `project3_production_jan.csv`
- `project3_production_feb.csv`
- `project3_production_mar.csv`
- `project3_machine_info.csv`
- `project3_operator_info.csv`

### 프로젝트 상황

제조기업에서 월별 생산 데이터, 설비 정보, 작업자 정보를 통합하여 불량률이 높은 조건을 파악하고 품질 분석용 데이터셋을 만들려고 합니다.

### 수행 조건

1. 1월, 2월, 3월 생산 데이터를 불러오시오.
2. 월별 생산 데이터를 `concat`으로 합치시오.
3. 데이터 구조, 결측치, 중복치를 확인하시오.
4. 중복치를 제거하시오.
5. 온도, 압력, 진동 결측치를 중앙값으로 처리하시오.
6. IQR 방식으로 진동 이상치를 확인하고 보정하시오.
7. 생산일자를 날짜형으로 변환하고 생산월, 생산요일을 생성하시오.
8. 생산 데이터와 설비 정보를 `merge`하시오.
9. 생산 데이터와 작업자 정보를 `merge`하시오.
10. `join`을 사용하여 생산 데이터에 설비 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.
11. `iloc`로 앞 5행과 일부 컬럼을 선택하시오.
11. `loc`로 야간 생산 데이터만 선택하시오.
12. 양품수량, 불량률, 설비연식, 고불량여부 변수를 생성하시오.
13. 불량률이 높은 야간 생산 데이터를 필터링하고 정렬하시오.
14. 라인과 교대별 평균 불량률을 집계하시오.
15. 숙련도를 순서형 인코딩하시오.
16. 제품유형, 교대, 라인, 설비유형을 원-핫 인코딩하시오.
17. 생산수량, 불량수량, 온도, 압력, 진동, 불량률을 스케일링하시오.
18. 최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.

In [1]:
import pandas as pd

# 1. 고객, 상품, Q1 주문, Q2 주문 데이터를 불러오시오.

In [2]:

df_cust = pd.read_csv('./data/project2_customers.csv', encoding = 'utf-8-sig')
df_prod = pd.read_csv('./data/project2_products.csv', encoding = 'utf-8-sig')
df_ordq1 = pd.read_csv('./data/project2_orders_q1.csv', encoding = 'utf-8-sig')
df_ordq2 = pd.read_csv('./data/project2_orders_q2.csv', encoding = 'utf-8-sig')

In [3]:
df_prod.head()

   상품ID  카테고리   브랜드     원가    판매가
0  3001    패션  A브랜드  39896  61987
1  3002  생활용품  C브랜드  12563  31416
2  3003    식품  D브랜드  12507  23950
3  3004    식품  A브랜드   8541  22285
4  3005    패션  B브랜드  42725  76215

In [4]:
df_cust.head()

   고객ID  성별  연령  지역 회원등급
0  2001  남성  30  서울   일반
1  2002  남성  22  서울   골드
2  2003  여성  51  경상   골드
3  2004  여성  29  서울   골드
4  2005  남성  33  경기   실버

In [5]:
df_ordq1.head()

       주문ID        주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부
0  Q1-00001  2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상
1  Q1-00002  2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상
2  Q1-00003  2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상
3  Q1-00004  2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상
4  Q1-00005  2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상

In [6]:
df_ordq2.head()

       주문ID        주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부
0  Q2-00001  2026-06-26  2009  3012   4  0.05    카드  모바일앱   환불
1  Q2-00002  2026-05-04  2081  3020   4  0.00    카드  모바일앱   정상
2  Q2-00003  2026-06-15  2059  3017   1  0.05   무통장  모바일앱   정상
3  Q2-00004  2026-05-13  2022  3037   4  0.10  간편결제  모바일앱   정상
4  Q2-00005  2026-06-05  2110  3049   5  0.10  계좌이체  오프라인   정상

# 2. Q1 주문 데이터와 Q2 주문 데이터를 `concat`으로 합치시오.

In [7]:
#2. Q1 주문 데이터와 Q2 주문 데이터를 `concat`으로 합치시오.
q1_q2 = pd.concat([df_ordq1,df_ordq2], ignore_index = True)
q1_q2.head()

       주문ID        주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부
0  Q1-00001  2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상
1  Q1-00002  2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상
2  Q1-00003  2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상
3  Q1-00004  2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상
4  Q1-00005  2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상

# 3. 결측치와 중복치를 확인하고 처리하시오.

In [8]:
q1_q2.isnull().sum()

주문ID     0
주문일자     0
고객ID     0
상품ID     0
수량       0
할인율     37
결제수단     0
판매채널     0
환불여부     0
dtype: int64

In [9]:
q1_q2['할인율'] = q1_q2['할인율'].fillna(0)

In [10]:
q1_q2.isnull().sum()

주문ID    0
주문일자    0
고객ID    0
상품ID    0
수량      0
할인율     0
결제수단    0
판매채널    0
환불여부    0
dtype: int64

In [11]:
q1_q2.duplicated().sum()

np.int64(10)

In [12]:
q1_q2 = q1_q2.drop_duplicates()
q1_q2.duplicated().sum()

np.int64(0)

# 4. 주문일자를 날짜형으로 변환하고 주문월, 요일 변수를 생성하시오.

In [13]:
from datetime import datetime, date
import numpy as np
week = np.array(['월','화','수','목','금','토','일'])
q1_q2["주문일자"] =pd.to_datetime(q1_q2['주문일자'], format='%Y-%m-%d') 
q1_q2['주문월']=q1_q2["주문일자"].dt.month
q1_q2['주문요일']=week[q1_q2["주문일자"].dt.weekday]
q1_q2.head()

       주문ID       주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부  주문월 주문요일
0  Q1-00001 2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상    2    목
1  Q1-00002 2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상    2    일
2  Q1-00003 2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상    1    금
3  Q1-00004 2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상    3    목
4  Q1-00005 2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상    2    토

# 5. 주문 데이터에 고객 정보를 `merge`하시오.

In [14]:
order_cust = pd.merge(q1_q2,df_cust, on = '고객ID', how = 'inner')
order_cust.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,성별,연령,지역,회원등급
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2,목,여성,18,경상,일반
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2,일,여성,42,전라,일반
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1,금,남성,31,경기,실버
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3,목,남성,30,충청,일반
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2,토,여성,27,서울,VIP

# 6. 주문 데이터에 상품 정보를 `merge`하시오.

In [15]:
order = pd.merge(order_cust,df_prod, on = '상품ID', how = 'inner')
order.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,성별,연령,지역,회원등급,카테고리,브랜드,원가,판매가
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2,목,여성,18,경상,일반,식품,C브랜드,9809,16670
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2,일,여성,42,전라,일반,식품,C브랜드,10960,20808
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1,금,남성,31,경기,실버,패션,D브랜드,36520,67712
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3,목,남성,30,충청,일반,패션,A브랜드,39896,61987
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2,토,여성,27,서울,VIP,식품,D브랜드,10234,22248

In [16]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문ID    970 non-null    object
 1   주문일자    970 non-null    datetime64[ns]
 2   고객ID    970 non-null    int64
 3   상품ID    970 non-null    int64
 4   수량      970 non-null    int64
 5   할인율     970 non-null    float64
 6   결제수단    970 non-null    object
 7   판매채널    970 non-null    object
 8   환불여부    970 non-null    object
 9   주문월     970 non-null    int32
 10  주문요일    970 non-null    object
 11  성별      970 non-null    object
 12  연령      970 non-null    int64
 13  지역      970 non-null    object
 14  회원등급    970 non-null    object
 15  카테고리    970 non-null    object
 16  브랜드     970 non-null    object
 17  원가      970 non-null    int64
 18  판매가     970 non-null    int64
dtypes: datetime64[ns](1), float64(1), int32(1), int64(6), object(10)
memory usage: 140.3+ KB

# 7. join을 사용하여 주문 데이터에 상품 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.

In [17]:
# join을 사용하여 주문 데이터에 상품 정보를 인덱스 기준으로 붙이기
product_info = df_prod.set_index('상품ID')

order_join = order.set_index('상품ID').join(product_info, how='left', rsuffix='_상품')
order_join.reset_index(inplace=True)
order_join.head()

,상품ID,주문ID,주문일자,고객ID,수량,할인율,결제수단,판매채널,환불여부,주문월,...,지역,회원등급,카테고리,브랜드,원가,판매가,카테고리_상품,브랜드_상품,원가_상품,판매가_상품
0,3045,Q1-00001,2026-02-12,2057,4,0.10,간편결제,모바일앱,정상,2,...,경상,일반,식품,C브랜드,9809,16670,식품,C브랜드,9809,16670
1,3044,Q1-00002,2026-02-22,2054,3,0.10,카드,모바일앱,정상,2,...,전라,일반,식품,C브랜드,10960,20808,식품,C브랜드,10960,20808
2,3048,Q1-00003,2026-01-30,2084,4,0.05,카드,모바일앱,정상,1,...,경기,실버,패션,D브랜드,36520,67712,패션,D브랜드,36520,67712
3,3001,Q1-00004,2026-03-05,2091,3,0.20,계좌이체,모바일앱,정상,3,...,충청,일반,패션,A브랜드,39896,61987,패션,A브랜드,39896,61987
4,3027,Q1-00005,2026-02-28,2142,4,0.05,계좌이체,웹,정상,2,...,서울,VIP,식품,D브랜드,10234,22248,식품,D브랜드,10234,22248

# 8. iloc로 앞 5행과 일부 컬럼을 선택하시오.

In [18]:
order.iloc[:5,[0,4,5,8,14,17,18]]

       주문ID  수량   할인율 환불여부 회원등급     원가    판매가
0  Q1-00001   4  0.10   정상   일반   9809  16670
1  Q1-00002   3  0.10   정상   일반  10960  20808
2  Q1-00003   4  0.05   정상   실버  36520  67712
3  Q1-00004   3  0.20   정상   일반  39896  61987
4  Q1-00005   4  0.05   정상  VIP  10234  22248

# 9. loc로 VIP 고객 주문만 선택하시오.

In [19]:
vip = order.loc[order['회원등급']=='VIP',:]
vip.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,성별,연령,지역,회원등급,카테고리,브랜드,원가,판매가
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2,토,여성,27,서울,VIP,식품,D브랜드,10234,22248
16,Q1-00017,2026-03-01,2017,3025,1,0.00,계좌이체,모바일앱,정상,3,일,남성,37,경기,VIP,식품,A브랜드,9870,25177
25,Q1-00026,2026-03-15,2142,3041,4,0.10,계좌이체,웹,정상,3,일,여성,27,서울,VIP,도서,D브랜드,13298,30884
33,Q1-00034,2026-03-14,2144,3035,5,0.15,카드,오프라인,정상,3,토,남성,18,서울,VIP,패션,C브랜드,42086,69807
39,Q1-00040,2026-03-03,2048,3050,2,0.10,계좌이체,웹,정상,3,화,여성,55,전라,VIP,식품,B브랜드,12489,25637

# 10. 총매출액, 할인액, 순매출액, 이익, 실매출액 변수를 생성하시오.

In [20]:
#상품ID	수량	할인율	환불여부	 원가	판매가

In [21]:
# 총매출액 = 수량*판매가
# 할인액 = 총매출액*할인율
#순매출액 = 총매출액 - 할인액
#이익 = 순매출액 - (원가*수량)
#실매출액 = 순매출액 - 환불량

In [22]:
order["총매출액"] = order["판매가"] * order["수량"]
order["할인액"] = order["총매출액"] * order["할인율"]
order["순매출액"] = order["총매출액"] - order["할인액"]
order["이익"] = order["순매출액"] - (order["원가"] * order["수량"])

order["실매출액"] = np.where(
    order["환불여부"] == "환불",
    0,
    order["순매출액"]
)
order.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,...,회원등급,카테고리,브랜드,원가,판매가,총매출액,할인액,순매출액,이익,실매출액
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2,...,일반,식품,C브랜드,9809,16670,66680,6668.0,60012.0,20776.0,60012.0
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2,...,일반,식품,C브랜드,10960,20808,62424,6242.4,56181.6,23301.6,56181.6
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1,...,실버,패션,D브랜드,36520,67712,270848,13542.4,257305.6,111225.6,257305.6
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3,...,일반,패션,A브랜드,39896,61987,185961,37192.2,148768.8,29080.8,148768.8
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2,...,VIP,식품,D브랜드,10234,22248,88992,4449.6,84542.4,43606.4,84542.4

# 11. 전자기기 카테고리의 고액 정상 주문을 필터링하고 정렬하시오.

In [1]:
result = order.query("카테고리 == '전자기기' and 환불여부 == '정상' and 판매가>=50000") #50000워 이상의 판매가를 고액으로 정함
elec_order = result.sort_values(by = ['판매가'], ascending = False)
elec_order.head()

NameError: name 'order' is not defined

# 12. 카테고리별 주문건수, 판매수량, 실매출액, 실이익을 집계하시오.

In [24]:
cat_sum = order.groupby('카테고리').agg(
    {
        '주문ID' : 'count',
        '수량' : 'sum', 
        '실매출액' : 'sum', 
        '이익' : 'sum'
    }
).rename(
    columns = {'주문ID' : '주문건수'}).reset_index()

cat_sum

   카테고리  주문건수   수량         실매출액           이익
0    도서   119  355   8119044.40   3805872.15
1  생활용품   167  491  13609012.70   7759076.55
2    식품   309  898  16885192.35   8808098.15
3  전자기기   145  406  75613824.90  43812338.60
4    패션   230  653  41640434.35  19386945.40

# 13. 회원등급을 순서형 인코딩하시오.

In [25]:
order['회원등급'].value_counts()

회원등급
일반     467
실버     259
골드     142
VIP    102
Name: count, dtype: int64

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le = LabelEncoder()
order['회원등급라벨'] = le.fit_transform(order['회원등급'])
order.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,...,카테고리,브랜드,원가,판매가,총매출액,할인액,순매출액,이익,실매출액,회원등급라벨
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2,...,식품,C브랜드,9809,16670,66680,6668.0,60012.0,20776.0,60012.0,3
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2,...,식품,C브랜드,10960,20808,62424,6242.4,56181.6,23301.6,56181.6,3
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1,...,패션,D브랜드,36520,67712,270848,13542.4,257305.6,111225.6,257305.6,2
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3,...,패션,A브랜드,39896,61987,185961,37192.2,148768.8,29080.8,148768.8,3
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2,...,식품,D브랜드,10234,22248,88992,4449.6,84542.4,43606.4,84542.4,0

# 14. 카테고리, 지역, 결제수단, 판매채널을 원-핫 인코딩하시오.

In [28]:
#부서_원핫 = pd.get_dummies(df['부서'],prefix = '부서', dtype = int)
#부서_원핫.head()

onehot_cols = ["카테고리", "지역", "결제수단", "판매채널"]

order_encoded = pd.get_dummies(
    order,
    columns = onehot_cols,
    dtype = int
)

order_encoded.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,환불여부,주문월,주문요일,성별,...,지역_서울,지역_전라,지역_충청,결제수단_간편결제,결제수단_계좌이체,결제수단_무통장,결제수단_카드,판매채널_모바일앱,판매채널_오프라인,판매채널_웹
0,Q1-00001,2026-02-12,2057,3045,4,0.10,정상,2,목,여성,...,0,0,0,1,0,0,0,1,0,0
1,Q1-00002,2026-02-22,2054,3044,3,0.10,정상,2,일,여성,...,0,1,0,0,0,0,1,1,0,0
2,Q1-00003,2026-01-30,2084,3048,4,0.05,정상,1,금,남성,...,0,0,0,0,0,0,1,1,0,0
3,Q1-00004,2026-03-05,2091,3001,3,0.20,정상,3,목,남성,...,0,0,1,0,1,0,0,1,0,0
4,Q1-00005,2026-02-28,2142,3027,4,0.05,정상,2,토,여성,...,1,0,0,0,1,0,0,0,0,1

# 15. 매출 관련 수치형 컬럼을 스케일링하시오.

In [29]:
order_encoded.columns

Index(['주문ID', '주문일자', '고객ID', '상품ID', '수량', '할인율', '환불여부', '주문월', '주문요일',
       '성별', '연령', '회원등급', '브랜드', '원가', '판매가', '총매출액', '할인액', '순매출액', '이익',
       '실매출액', '회원등급라벨', '카테고리_도서', '카테고리_생활용품', '카테고리_식품', '카테고리_전자기기',
       '카테고리_패션', '지역_강원', '지역_경기', '지역_경상', '지역_서울', '지역_전라', '지역_충청',
       '결제수단_간편결제', '결제수단_계좌이체', '결제수단_무통장', '결제수단_카드', '판매채널_모바일앱',
       '판매채널_오프라인', '판매채널_웹'],
      dtype='object')

In [30]:
# 총매출액, 할인액, 순매출액, 이익, 실매출액
from sklearn.preprocessing import MinMaxScaler

scale_cols = ["총매출액", "할인액", "순매출액", "이익", "실매출액"]
scaler = MinMaxScaler()
df_input_model = order_encoded.copy()
df_input_model[scale_cols] = scaler.fit_transform(df_input_model[scale_cols])

df_input_model.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,환불여부,주문월,주문요일,성별,...,지역_서울,지역_전라,지역_충청,결제수단_간편결제,결제수단_계좌이체,결제수단_무통장,결제수단_카드,판매채널_모바일앱,판매채널_오프라인,판매채널_웹
0,Q1-00001,2026-02-12,2057,3045,4,0.10,정상,2,목,여성,...,0,0,0,1,0,0,0,1,0,0
1,Q1-00002,2026-02-22,2054,3044,3,0.10,정상,2,일,여성,...,0,1,0,0,0,0,1,1,0,0
2,Q1-00003,2026-01-30,2084,3048,4,0.05,정상,1,금,남성,...,0,0,0,0,0,0,1,1,0,0
3,Q1-00004,2026-03-05,2091,3001,3,0.20,정상,3,목,남성,...,0,0,1,0,1,0,0,1,0,0
4,Q1-00005,2026-02-28,2142,3027,4,0.05,정상,2,토,여성,...,1,0,0,0,1,0,0,0,0,1

# 16. 최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.

In [31]:
order.to_csv('./Data/order_analysis.csv', index=False)
df_input_model.to_csv('./Data/order_input_model.csv', index=False)